defmodule AshFkNameRepro.Repo.Migrations.CreateResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:children, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:ref_parent, :uuid, null: false)
    end

    create table(:parents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:children) do
      modify(
        :ref_parent,
        references(:parents,
          column: :id,
          name: "children_ref_parent_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create table(:working_children, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:ref_parent, :uuid, null: false)
    end

    create table(:working_parents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:working_children) do
      modify(
        :ref_parent,
        references(:working_parents,
          column: :id,
          name: "working_children_parent_ref_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end
  end

  def down do
    drop(constraint(:working_children, "working_children_parent_ref_fkey"))

    alter table(:working_children) do
      modify(:ref_parent, :uuid)
    end

    drop(table(:working_parents))

    drop(table(:working_children))

    drop(constraint(:children, "children_ref_parent_fkey"))

    alter table(:children) do
      modify(:ref_parent, :uuid)
    end

    drop(table(:parents))

    drop(table(:children))
  end
end
